version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: "15:00"
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
      time: "15:00"