[package]
name = "expo_push_notification_client"
version = "0.3.4"
edition = "2021"
readme = "README.md"
authors = ["katayama8000 <https://github.com/katayama8000>"]
description = "Expo Push Notification Client for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/katayama8000/expo-push-notification-client"
homepage = "https://github.com/katayama8000/expo-push-notification-client/blob/main/README.md"
keywords = ["react", "native", "expo", "push", "notifications"]
categories = ["api-bindings", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = { version = "0.4.6", features = ["gzip", "tokio"] }
regex = "1.10.3"
reqwest = { version = "0.12.2", features = ["json", "gzip"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_with = "3.6.0"
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["io-util"] }

[dev-dependencies]
anyhow = "1.0.79"
mockito = "1.4.0"
tokio = { version = "1.36.0", features = ["full"] }
